### ISSUE TITLE
Improve Readme?

### ISSUE THREAD

**Issue by dufferzafar** [aviaryan/playlist-dl#1]
Hey, I don't mean to put down your work, but I think you should make it a bit more clear what the application does differently (or better) than youtube-dl.

I use youtube-dl a lot for downloading videos and playlists, and I think it already has support for a lot of options, so I can't figure out what problem will this application solve for me.

Again, I don't mean to sound rude or anything, just hope you could clear out the usecase.

**Comment by aviaryan** [comment]
You are right.
The one main feature that this program is useful is when you want to download say 480p videos. Now some videos in playlist may have format_code X,Y in 480p but some may have format_code Z in 480p. Also some may not even have 480p format.
In that case youtube-dl may fail with the `-f option`. On the other hand, this program will scan all formats available of the video and try to give you 480p in any format. If it fails, it will automatically use the bestvideo format. Same happens for audio. You can keep bitrate to 128 if you are sure higher bitrates won't be much useful.

I am not on the fastest of Internet connections so such optimizations really help me save some time.

**Comment by dufferzafar** [comment]
I am on exactly the same internet connection as you (perhaps even worse) so I can clearly see where you're coming from. 

The changes you suggest are really nice. 

I think all you need to do is just make a section ("Customizations over youtube-dl?") and just explain this part out so people know if they actually need this or not.

**Comment by dufferzafar** [comment]
Also, I think if a video is not found in the 480p format, it should just download the best video format LESS than 480p, because If someone doesn't want 720p that's most likely because they are on a capped data connection (that's me.)

**Comment by aviaryan** [comment]
I was just reading https://github.com/rg3/youtube-dl/#format-selection and found that almost all of these features are already supported by youtube-dl. In that case, my script is useless.. I can write a bash script and do the same job. I was in urgent need of something like this yesterday so I made this script. :pensive:

**Comment by dufferzafar** [comment]
eh! that happens with the best of us. I wouldn't worry about it. Just keep your repo as is, and forget about it. :)
